apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  labels:
    tier: front-end-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: nginx-pod
    where: frontend
