apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    what: daemonsets
spec:
  selector:
    matchLabels:
      app: fluentd-daemonsets
  template:
    metadata:
      name: elasticsearch
      labels:
        app: fluentd-daemonsets
    spec:
      containers:
        - name: elasticsearch-container
          image: k8s.gcr.io/fluentd-elasticsearch:1.20
