apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
  labels:
    tier: front-end
    type: loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
