apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    name: yellow
    tier: frontend
spec:
  containers:
    - name: lemon
      image: busybox
      ports:
        - containerPort: 8080
    - name: gold
      image: redis
