apiVersion: v1
kind: ReplicationController
metadata:
  name: my-first-rc
  labels:
    name: test-rc
    images: nginx
spec:
  template:
    metadata:
      name: my-nginx-pod
      labels:
        name: frontend-nginx-pod
    spec:
      containers:
        - name: my-nginx-pod
          image: nginx
  replicas: 3