apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  labels:
    kind: service-nodeport
    what: expose-my-nginx-pod
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
      type: nginx-pod
      where: frontend

