apiVersion: v1
kind: Service
metadata:
  name: node-port-service-1
  labels:
    kind: service-nodeport
    what: expose-my-webappcolor-pod
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30102
  selector:
      name: webapp-color

