apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-rs
    labels:
        tier: frontend
spec:
    replicas: 4
    selector:
        matchLabels:
            tier: frontend
    template:
        metadata:
            name: busybox-container
            labels:
                name: busybox-container
                tier: frontend
        spec:
            containers:
                - name: busybox-container
                  image: busybox
