apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
    tier: frontend
spec:
  containers:
    - name: webapp-pod
      image: kodekloud/simple-webapp-mysql
      envFrom:
        - secretRef:
            name: db-secret