apiVersion: v1
kind: Pod
metadata:
  name: toint-tolerations
  labels:
    purpose: taint-toleration-spray
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "spray"
      operator: "Equal"
      value: "mortein"
      effect: "NoSchedule"