apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
spec:
  metadata:
    name: akshay
  spec:
    signerName: kubernetes.io/kube-apiserver-client
    groups:
      - system:authenticated
      request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXhZTlZnTy9ocnFSTDNwbHN2ay8rdVZGS3N6NEpmQWltZEdMZU9nUmZIRTN2CnNEU2ZlYm83MXFiZ3JBWWhIY1ZNUlJiaGptQm1INjMzV3I2SDdabFZOQ0J0SStvU3Vaelo0ZFkwUjF3ajVFbG4KckdPakw1dnR2Um1PLzNOczFmL3FUQ3JtUmZYODh3TVpsOE15cGxPY0Rwajk4SXBtRDc2Y3BUOWZwMTQ0cVVNbAo3RFdOVlNhY0FkWU9ONS9Ca2tMQ2xmc0EwTWl6VmVGT2xBYkovaHFyTHUzREQxZXplSWtDc1A5dDlpOGlFWXRnClpXdkV3MEhMbWpCUDNKa3REb3ZxR2d2c09nY2J4SlhFcUczYzUwTEdLOVNhQWd5YktYdVB3QjZ5d3pXRG9ONE0KK3RvdzMrUm4xMWJLYmhxNUlLVzg3VWwzMzBzN000cW9CTjJ2TDFTNUt3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSGVVU3RxR2o1YlcwWStuZWNGRzJ6cWM5cWVxTE9JNTEyK1Q4YzlxcE5Td0Z1aEdmbGI5CmFGK2pWc0tmSEpzSVg3anEwNFBTL2ptUWVRK2UyWlRkVFNaTHE2aUQ5VFV2TXJ0Nk1YU2xQckZnNERpSS9kUFYKWi9xbmE5dnBiT3NPVS9wMWhIdTc0TUdwYmN0SHBqMnk3N2JnVDlZUzFvYTVCWTVKNlZLNEdUeUMxVzNuN2ZYSApzSmFnWUJwcHcrS2srM1h4cVB4c0hQQ2daWHdiVHJCWk4wd2FmZDBaSndHZkhOdW5odW9nWGRZbkc2WnFJN3hXCmRPNDUxdGxPMlFyUTRkTG4zZzVnNHZmcnU0SXBZZ2l0UHZ0c0V2MWdsQWF2SWFiWGtHRElzbWNwVE1GZG5LekgKbFlaMnRZR3NDcnpCUDBsRGt3M0hDTForKzIvdUx3ekZDSGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
      usages:
        - digital signature
        - key encipherment
        - server auth