apiVersion: v1
kind: Service
metadata:
  name: externalip-service
spec:
  selector:
    name: my-nginx-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
  externalIPs:
    - 80.11.12.10