apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    name: np-service
spec:
  type: NodePort
  selector:
    type: mc-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
