apiVersion: v1
kind: Service
metadata:
  labels:
    name: my-service
  name: my-cluster-ip-service
spec:
  selector:
    name: my-nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

